services:
  backend:
    image: "faikyoussef/devops-demo:16.3.2023.13.29.42"
    ports:
      - "80:8080"
    restart: "always"
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: youssef
      POSTGRES_PASSWORD: faik
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres/:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
volumes:
  postgres:
  pgadmin:
